vich_uploader:
    db_driver: orm

    mappings:
       rgraphics_images:
           uri_prefix: /images/services
           upload_destination: '%kernel.project_dir%/public/images/services'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer