vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       rgraphics_images:
           uri_prefix: /images/services
           upload_destination: '%kernel.project_dir%/public/images/services'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       rgraphics_logo:
            uri_prefix: /images/parametre
            upload_destination: '%kernel.project_dir%/public/images/parametre'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    
       rgraphics_membres:
            uri_prefix: /images/membre
            upload_destination: '%kernel.project_dir%/public/images/membre'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
