controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_administration:
    path: '/administration'
    controller: 'App\Controller\AdministrationController::addContent'
    methods: ['GET','POST']